select * from board;

-- 회원 테이블 --
CREATE TABLE MEMBER(
	MEMIDX INT NOT NULL,
	MEMID VARCHAR(20) NOT NULL,
	MEMPW VARCHAR(70) NOT NULL,
	MEMNAME VARCHAR(20) NOT NULL,
	MEMAGE INT,
	MEMGENDER VARCHAR(20),
	MEMEMAIL VARCHAR(50),
	MEMPROFILE VARCHAR(50),
	PRIMARY KEY(MEMID)
);

-- 권한 테이블
-- Spring Security에서는 member테이블 안에 반드시 권한이 있어야 함
-- 사용하지 않더라도 넣어주자!
CREATE TABLE AUTH(
	NO INT NOT NULL AUTO_INCREMENT,
	MEMID VARCHAR(50) NOT NULL,
	AUTH VARCHAR(50) NOT NULL,
	PRIMARY KEY(NO),
	CONSTRAINT FK_MEMBER_AUTH FOREIGN KEY(MEMID)
	REFERENCES MEMBER(MEMID)
);
select * from auth;
SELECT * FROM MEMBER;
DROP TABLE MEMBER;
DROP TABLE AUTH;

INSERT INTO MEMBER(MEMID, MEMPW, MEMNAME, MEMAGE, MEMGENDER, MEMEMAIL, MEMPROFILE)VALUES(
	'admin', '12345', '관리자',22,'여자','admin@gamil.com',''
);

DELETE FROM MEMBER WHERE MEMIDX=11;

DROP TABLE MEMBER;

CREATE TABLE BOARD(
	IDX INT NOT NULL AUTO_INCREMENT,
	MEMID VARCHAR(20) NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	CONTENT VARCHAR(2000) NOT NULL,
	WRITER VARCHAR(30) NOT NULL,
	INDATE DATETIME DEFAULT NOW(),
	COUNT INT DEFAULT 0,
	PRIMARY KEY(IDX)
);
select * from board;
DELETE FROM MEMBER;
