select * from board;

-- 회원 테이블 --
CREATE TABLE MEMBER(
	MEMIDX INT AUTO_INCREMENT,
	MEMID VARCHAR(20) NOT NULL,
	MEMPW VARCHAR(20) NOT NULL,
	MEMNAME VARCHAR(20) NOT NULL,
	MEMAGE INT,
	MEMGENDER VARCHAR(20),
	MEMEMAIL VARCHAR(50),
	MEMPROFILE VARCHAR(50),
	PRIMARY KEY(MEMIDX)
);

SELECT * FROM MEMBER;
DROP TABLE MEMBER;

INSERT INTO MEMBER(MEMID, MEMPW, MEMNAME, MEMAGE, MEMGENDER, MEMEMAIL, MEMPROFILE)VALUES(
	'admin', '12345', '관리자',22,'여자','admin@gamil.com',''
);

DELETE FROM MEMBER WHERE MEMIDX=6;

DROP TABLE BOARD;

CREATE TABLE BOARD(
	IDX INT NOT NULL AUTO_INCREMENT,
	MEMID VARCHAR(20) NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	CONTENT VARCHAR(2000) NOT NULL,
	WRITER VARCHAR(30) NOT NULL,
	INDATE DATETIME DEFAULT NOW(),
	COUNT INT DEFAULT 0,
	PRIMARY KEY(IDX)
);
select * from board;